# Generated by Django 5.1.3 on 2024-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0003_division_in_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], default='M', max_length=1),
        ),
    ]
